# Generated by Django 6.0.1 on 2026-03-11 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('P', 'Prefiero mantenerlo privado')], max_length=1)),
                ('rol', models.CharField(choices=[('estudiante', 'Estudiante'), ('docente', 'Docente'), ('investigador', 'Investigador'), ('administrativo', 'Administrativo'), ('otro', 'Otro')], max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
