# Generated by Django 6.0.1 on 2026-03-10 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenValidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='imagenes_validacion/')),
                ('imagen_base64', models.TextField(blank=True, null=True)),
                ('tipo_origen', models.CharField(choices=[('IA', 'Imagen generada por IA'), ('NO_IA', 'Imagen no generada por IA')], max_length=10)),
                ('seleccionada', models.BooleanField(default=False)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('subida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
