# Generated by Django 6.0.1 on 2026-03-10 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PruebaImagenRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(choices=[('IA', 'Imagen por IA'), ('SINTETICA', 'Sintética')], max_length=20)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validacion.imagenvalidacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
