# Generated by Django 6.0.1 on 2026-03-10 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validacion', '0002_pruebaimagenrespuesta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pruebaimagenrespuesta',
            name='es_correcta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imagenvalidacion',
            name='tipo_origen',
            field=models.CharField(choices=[('IA', 'Imagen generada por IA'), ('NO_IA', 'Sintética')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pruebaimagenrespuesta',
            name='respuesta',
            field=models.CharField(choices=[('IA', 'IA'), ('NO_IA', 'SINTÉTICA')], max_length=20),
        ),
        migrations.CreateModel(
            name='SesionPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('finalizada', models.BooleanField(default=False)),
                ('destinatario', models.CharField(blank=True, choices=[('DR_JORGE', 'Dr. Jorge'), ('LUCIANO', 'Luciano')], max_length=20, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pruebaimagenrespuesta',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='validacion.sesionprueba'),
        ),
    ]
