# Generated by Django 6.0.1 on 2026-03-11 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_participantepublico'),
        ('validacion', '0003_pruebaimagenrespuesta_es_correcta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionPruebaPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('finalizada', models.BooleanField(default=False)),
                ('destinatario', models.CharField(blank=True, choices=[('DR_JORGE', 'Dr. Jorge'), ('LUCIANO', 'Luciano')], max_length=20, null=True)),
                ('participante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_publicas', to='inicio.participantepublico')),
            ],
        ),
        migrations.CreateModel(
            name='PruebaImagenRespuestaPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(choices=[('IA', 'IA'), ('NO_IA', 'SINTÉTICA')], max_length=20)),
                ('es_correcta', models.BooleanField(default=False)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validacion.imagenvalidacion')),
                ('participante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_publicas', to='inicio.participantepublico')),
                ('sesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='validacion.sesionpruebapublica')),
            ],
        ),
    ]
